### ISSUE TITLE
Error with newer version of Common.Logging

### ISSUE THREAD

**Issue by nelittle** [gridsum/DataflowEx#3] opened 2015-07-28 18:40 UTC
I got an error when using a newer version of Common.Logging and Common.Logging.Core System.TypeInitializationException : The type initializer for 'Gridsum.DataflowEx.LogHelper' threw an exception.
  ----> System.TypeLoadException : Could not load type 'Common.Logging.LogManager' from assembly 'Common.Logging.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e'.
   at Gridsum.DataflowEx.LogHelper.get_Logger()
   at Gridsum.DataflowEx.Dataflow.<GetCompletionTask>d__18.MoveNext()

i got the same issue using 3.1 and 3.2 of the frameworks.

i was able to get past that issue by revering Common.Logging.Core to 2.2 and updating my app.config.  
It looks like they had similar problems with an earlier version: https://github.com/net-commons/common-logging/issues/23

but that should be fixed in 2.2 according to that thread. Not sure what the root problem is here or if maybe a new version of DataflowEx should be published with updated references to the logging frameworks.

**Comment by nelittle** [comment] 2015-07-28 18:42
here is the full stack trace:
System.TypeInitializationException : The type initializer for 'Gridsum.DataflowEx.LogHelper' threw an exception.
  ----> System.TypeLoadException : Could not load type 'Common.Logging.LogManager' from assembly 'Common.Logging.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e'.
   at Gridsum.DataflowEx.LogHelper.get_Logger()
   at Gridsum.DataflowEx.Dataflow.<GetCompletionTask>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dataflow.Tests.AvailableScheduleBlockFlowTests.<GetAvailabilityTest>d__1.MoveNext() in C:\Projects\AdvancedHealth\skedge.service\Tests\Dataflow.Tests\AvailableScheduleBlockFlowTests.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at NUnit.Framework.AsyncSynchronizationContext.AsyncOperation.Invoke()
   at NUnit.Framework.AsyncSynchronizationContext.AsyncOperationQueue.InvokePendingOperations()
   at NUnit.Framework.AsyncSynchronizationContext.AsyncOperationQueue.InvokeAll()
   at NUnit.Framework.AsyncInvocationRegion.AsyncVoidInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.AsyncInvocationRegion.AsyncVoidInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
--TypeLoadException
   at Gridsum.DataflowEx.LogHelper..cctor()

**Comment by karldodd** [comment] 2015-08-12 03:04
Thanks for reporting the issue @nelittle .

I think the reason behind the issue is a common.logging breaking change: the LogManager class has moved from Common.Logging.Core to Common.Logging, a different assembly.

Honestly DataflowEx may not update its common.logging dependency until next version. So, if downgrading to 2.2 is acceptable in your scenario, this is probably the best way to work around. Do you need any particular feature in common.logging 3.0+?

**Comment by hangy** [comment] 2016-01-07 12:51
Would it make sense to update the NuGet package to explicitly depend on Common.Logging >= 2.2.0 && < 3.0 in order to disallow incompatible upgrades?

**Comment by nelittle** [comment] 2016-01-07 14:22
i'm no longer working on this project, but the issue we had is that another package we were using was on a much newer version, hence us having that version already installed, so we ended up having to degrade several components version of Common.Logging. It seemed to work for us, but if any of those other components had a min version dependency that was higher, i'm not sure what we would have done.

**Comment by karldodd** [comment] 2016-03-08 05:53
Recently I am planning to upgrade to Common.Logging 3.0 and publish a new version : )

Btw, porting the whole DataflowEx to .NET Core is also on the roadmap. This project will evolve.

**Comment by stristan** [comment] 2016-04-16 15:35
I'm also have an issues with Common.Logging. So wait for the new version. Can you update a status?

**Comment by karldodd** [comment] 2017-07-09 09:38
Hi guys, a brand new version of DataflowEx is out with the help of .Net Core preview 2 ! Please try out the preview release to see if it solves your problems (Common.Logging upgraded to 3.4.0) :

https://www.nuget.org/packages/Gridsum.DataflowEx/2.0.0-alpha

Cheers,

**Comment by karldodd** [comment] 2017-12-31 16:38
DataflowEx 2.0.0 with Common.Logging 3.4 was released. So close this issue.

**Closed by karldodd** 2017-12-31 16:38 UTC
Labels: done, enhancement
